### ISSUE TITLE
Radius of the bubble

### ISSUE THREAD

**Issue by hamza005** [Microsoft/powerbi-visuals-enhancedscatter#19]
How can I reduce the radius of the bubble in it? Kindly explain.

**Comment by hamza005** [comment]
do I have to play with `getBubbleRadius()` function to reduce the size of the bubbe radius? If so, then how's it possible?

**Comment by uve** [comment]
@hamza005, getBubbleRadius function calculates radius of bubble based on your dataset and window size. How do you want to change this behavior?

**Comment by hamza005** [comment]
I just want to reduce the size of bubble in scatter chart. the minimum size of bubble is still very big for me. I just want that bubble to nearly equal to a dot.

**Comment by uve** [comment]
@hamza005, try to fork this repository and modify getBubbleRadius function to make all bubbles smaller.

**Comment by hamza005** [comment]
@uve I have done this. But when I build the package and deploy, it again gets the previous size... I think i'm missing the exact thing to do. Actually, to be very sorry, I'm new on visuals, so kindly can you do this for me? make the radius small and just hint me up with the exact lines to be changed in the getBubbleRadius Function?

**Comment by hamza005** [comment]
Thanks @uve It's working now 👍
