### ISSUE TITLE
Symmetry shading

### ISSUE THREAD

**Issue by hamza005** [Microsoft/powerbi-visuals-enhancedscatter#22]
Hello! I want to add Symmetry Shading in my custom Scattered chart in Analytics panel? how can I do this?

**Comment by helen508light** [comment]
hi @hamza005 
now this behavior couldn't be implemented from the visual's code. It is not supported by powerBI yet

**Comment by hamza005** [comment]
hi @helen508light 
I've implemented this line in my enhancedScatter visual, It's just about to append a line in svg.

**Comment by helen508light** [comment]
@hamza005 
your question had sound like definitions for Analytics panel options from the code

**Comment by hamza005** [comment]
Yes, I couldn't do it in analytics panel so I just handled it in format pane. with a switch to on or off that line and a numeric value as input as the starting point of the line.
