### ISSUE TITLE
Draw Line from origin

### ISSUE THREAD

**Issue by hamza005** [Microsoft/powerbi-visuals-enhancedscatter#24]
Hello, I want to add a static regression line from origin to increasing toward x and y axis just like [this](https://bl.ocks.org/ctufts/298bfe4b11989960eeeecc9394e9f118). How can I do this?

**Comment by helen508light** [comment]
@hamza005 
you just need to use dataPoint.x and dataPoint.y except x and y in the example. General logic is the same

**Comment by hamza005** [comment]
This has been done since it was questioned. Thank you for you response.
