### ISSUE TITLE
X-Axis dont display Dates correctly

### ISSUE THREAD

**Issue by LarethianWilli** [microsoft/powerbi-visuals-enhancedscatter#37]
![ENHANCED SCATTER PROBLEM](https://user-images.githubusercontent.com/45950172/59068276-c0e67c00-8881-11e9-9f65-be652f5257a9.png)

as you can see in the image
I have an X-axis to see the Date, we have an Y-axis to count number of items (total), and z-value to determine how big the (xi,yi) point should be (Weighted Value). Apart I have a legend for the Market and I want to have details on the Date.

There are two problems for my scenario:
A) X-Axis doesnt display dates, like some other scatter chars available in the market,
B) The reason I think that happen it is because we are force to Group X-Axis with Earliest or Latest, instead of having them ungroup.

Can you guys improve this to not Summarize? and to display date labels in the X-Axis?

Thanks in advance for the time and effort.

Best regards

Larethian

**Comment by LarethianWilli** [comment]
To whom it may concern, 

Thanks for trying to fix this issue, I was super excited to download this morning the latest version of it and see the results, but unfortunately the problem still remain.
![ENHANCED SCATTER PROBLEM STILL THERE](https://user-images.githubusercontent.com/45950172/59928580-0cb22d00-940d-11e9-9cfb-50b654cfa409.png)

Or I do not know how to take it away :(

I can upload a set of test data that i am using so anyone else can point me out in the right direction

**Comment by helen508light** [comment]
Thank you for feedback
Please, sent the sample report to pbicvsupport@microsoft.com

**Comment by uve** [comment]
The bug was fixes in the latest release.
New version of the visual will reach the production environment July, 9th
